language: php

php:
    - 7.1
    - 7.2
    - nightly

env:
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.0.*

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer update --prefer-dist
    - composer require symfony/property-access:${SYMFONY_VERSION} --no-interaction --update-with-all-dependencies --prefer-dist

script:
    - composer validate --strict
